stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  tags:
    - shared
  script:
    - docker compose -p personalproject down || true
    - docker compose -p personalproject up --build --remove-orphans -d