stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  tags:
    - shared
  script:
    - docker system prune -f --volumes && docker compose -p aspnetdemo up --build --remove-orphans --detach
