//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CarService {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CarService() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Resources.Views.CarService", typeof(CarService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture)!;
            }
        }
        
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture)!;
            }
        }
        
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture)!;
            }
        }
        
        public static string AddVehicle {
            get {
                return ResourceManager.GetString("AddVehicle", resourceCulture)!;
            }
        }
        
        public static string CreateOrder {
            get {
                return ResourceManager.GetString("CreateOrder", resourceCulture)!;
            }
        }
        
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture)!;
            }
        }
        
        public static string Workshop {
            get {
                return ResourceManager.GetString("Workshop", resourceCulture)!;
            }
        }
        
        public static string Mechanic {
            get {
                return ResourceManager.GetString("Mechanic", resourceCulture)!;
            }
        }
        
        public static string LicensePlate {
            get {
                return ResourceManager.GetString("LicensePlate", resourceCulture)!;
            }
        }
        
        public static string Mileage {
            get {
                return ResourceManager.GetString("Mileage", resourceCulture)!;
            }
        }
        
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture)!;
            }
        }
        
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture)!;
            }
        }
        
        public static string FinalPrice {
            get {
                return ResourceManager.GetString("FinalPrice", resourceCulture)!;
            }
        }
        
        public static string PaymentStatus {
            get {
                return ResourceManager.GetString("PaymentStatus", resourceCulture)!;
            }
        }
        
        public static string StatusHistory {
            get {
                return ResourceManager.GetString("StatusHistory", resourceCulture)!;
            }
        }
        
        public static string RepairPhotos {
            get {
                return ResourceManager.GetString("RepairPhotos", resourceCulture)!;
            }
        }
        
        public static string NoPhotosYet {
            get {
                return ResourceManager.GetString("NoPhotosYet", resourceCulture)!;
            }
        }
        
        public static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture)!;
            }
        }
        
        public static string NavVehicles {
            get {
                return ResourceManager.GetString("NavVehicles", resourceCulture)!;
            }
        }
        
        public static string NavOrders {
            get {
                return ResourceManager.GetString("NavOrders", resourceCulture)!;
            }
        }
        
        public static string NavPayments {
            get {
                return ResourceManager.GetString("NavPayments", resourceCulture)!;
            }
        }
        
        public static string NavMechanicPanel {
            get {
                return ResourceManager.GetString("NavMechanicPanel", resourceCulture)!;
            }
        }
        
        public static string NavAdmin {
            get {
                return ResourceManager.GetString("NavAdmin", resourceCulture)!;
            }
        }
        
        public static string AdminPanel {
            get {
                return ResourceManager.GetString("AdminPanel", resourceCulture)!;
            }
        }
        
        public static string AdminDashboard {
            get {
                return ResourceManager.GetString("AdminDashboard", resourceCulture)!;
            }
        }
        
        public static string AdminServiceOrders {
            get {
                return ResourceManager.GetString("AdminServiceOrders", resourceCulture)!;
            }
        }
        
        public static string AdminWorkshops {
            get {
                return ResourceManager.GetString("AdminWorkshops", resourceCulture)!;
            }
        }
        
        public static string AdminMechanics {
            get {
                return ResourceManager.GetString("AdminMechanics", resourceCulture)!;
            }
        }
        
        public static string AdminServices {
            get {
                return ResourceManager.GetString("AdminServices", resourceCulture)!;
            }
        }
        
        public static string AdminSpareParts {
            get {
                return ResourceManager.GetString("AdminSpareParts", resourceCulture)!;
            }
        }
        
        public static string BackToSite {
            get {
                return ResourceManager.GetString("BackToSite", resourceCulture)!;
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture)!;
            }
        }
    }
}
